### ISSUE TITLE
Stale closure bug in useDecision

### ISSUE THREAD

**Issue by fabb** [optimizely/react-sdk#170] opened 2022-06-15 14:15 UTC
I'm running into a stale closure bug in my application. My component with the `useDecision` hook rerenders multiple times (on purpose) and during one of the last rerenders, the `overrides` (3rd parameter) to the `useDecision` hook change (on purpose). I have an experiment that targets this exact user attribute. When setting breakpoints, I can see that the experiment is activated, and then directly deactivated again (I have `autoUpdate` active which I need due to the changing user attributes).

I found that the last deactivation is caused by the [1st `useEffect` callback in the `useDecision` hook function](https://github.com/optimizely/react-sdk/blob/2.8.1/src/hooks.ts#L234). It calls an [old stale version of `getCurrentDecision`](https://github.com/optimizely/react-sdk/blob/2.8.1/src/hooks.ts#L243) which uses old stale `overrideAttrs` which are not up-to-date and are missing the `overrides` I provided in the last call to `useDecision`.

You have a stale closure problem because you are violating the rules of hooks. The function `getCurrentDecision` is not part of the dependency array of the `useEffect`. You need to find a way to solve this, probably using a `useRef` to use an up-to-date version of that function. (unfortunately [`useEvent`](https://github.com/reactjs/rfcs/blob/useevent/text/0000-useevent.md) has not yet been released, but maybe you could use a polyfill).

**Comment by rafinutshaw-optimizely** [comment] 2023-07-05 12:58
Hi @fabb, Thanks for raising this issue. It will be very helpful if you could provide an example scenario where this exact problem occurs so that we can look into it thoroughly.

Thanks!

**Comment by russell-loube-optimizely** [comment] 2023-07-24 18:56
Hi @fabb , apologies for the very prolonged delays with initial feedback on this. Are you able to provide some example scenarios (e.g., code snippets) where this occurs? We're unfortunately unable to continue analyzing without some more information. We hope to hear from you soon.

**Comment by mikechu-optimizely** [comment] 2023-12-08 21:27
I worked through using useDecision with (randomly) overriding the userId, but was unable to reproduce a race condition, at least in my contrived React app setup. I also cross-referenced our tickets to find where other clients may have reported stale decision.

Thanks for linking and to the point in code where the rule of hooks was violated. 
Perhaps you could give a PR to outline your solution?   
Or do you have a repo that you can link to me showing the reproducible scenario instead of my lame setup?  
Did you work around the problem and can provide guidance there?

**Comment by mikechu-optimizely** [comment] 2023-12-08 21:37
Oop, found another work ticket (FSSDK-9624) and more importantly, related Issue #196 and PR #184.  That's helpful.

**Comment by mikechu-optimizely** [comment] 2023-12-09 08:36
Thanks for providing the history and your honest feedback.

I'll work this issue via the other GH reports, closing this issue to reduce noise.

**Closed by mikechu-optimizely** 2023-12-09 08:36 UTC
Labels: wip, acknowledged
