### ISSUE TITLE
createInstance fns.assignIn is not a function

### ISSUE THREAD

**Issue by Mskalba** [optimizely/react-sdk#14] opened 2019-11-18 22:13 UTC
Hello,

I am trying to setup optimizely for react application. I am using react 16.9.0 and @optimizely/react-sdk 1.0.0.

I wrapped whole application with OptimizelyProvided as stated in documentation:

```
const optimizely = createInstance({
  sdkKey: "MY-SDK-KEY-I-CHECKED-ITS-CORRECT",
});

class App extends React.Component {
  render() {
    return (
      <OptimizelyProvider
        optimizely={optimizely}
        user={{
          id: "test-123",
          attributes: {
            "customerId": 123,
            "Location": "poland",
          },
        }}>
      ...
```

But during initialization I get an error in this part of your source code:

It start here:
```
this._client = optimizely.createInstance(configWithClientEngine);
```
Then inside that function I found out that fns.assignIn is not a function, it is a module.
```
config = fns.assignIn(
        {
          clientEngine: enums.JAVASCRIPT_CLIENT_ENGINE,
          eventBatchSize: DEFAULT_EVENT_BATCH_SIZE,
          eventFlushInterval: DEFAULT_EVENT_FLUSH_INTERVAL,
        },
        config,
        {
          eventDispatcher: eventDispatcher,
          // always get the OptimizelyLogger facade from logging
          logger: logger,
          errorHandler: logging.getErrorHandler(),
        }
      );
```
which leads us to situation where 

```
this._client
```
is null, and in below line the onReady function on null cannot be triggered

```
this.dataReadyPromise = Promise.all([this.userPromise, this._client.onReady()])
```

May this issue be connected with webpack configuration? Could you help me with that problem?

**Comment by timclark97** [comment] 2020-02-20 14:24
I am also getting this error when trying to use `createInstance`. On v1.1.0.

**Comment by timclark97** [comment] 2020-02-21 20:40
Discovered this was caused by an an alias we gave to lodash in our webpack config. Removing the alias resolved the issue.

**Comment by Tautorn** [comment] 2020-10-07 20:29
I'm using v2.0.0 and work for me.

```
const optimizely = createInstance({
  sdkKey: process.env.REACT_APP_OPTIMIZELY
})

 <OptimizelyProvider optimizely={optimizely} user={user}>
      {children}
    </OptimizelyProvider>

```

**Comment by Danny-Driscoll** [comment] 2021-12-14 23:30
Closing, lodash dependency has been removed for JS since v4.0 and React SDK since v2.0

**Closed by Danny-Driscoll** 2021-12-14 23:30 UTC
